import "./globals.css";
import type { Metadata } from "next";
import { Ubuntu_Mono } from "next/font/google";

const roboto = Ubuntu_Mono({
  weight: "700",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-pink-50 text-black dark:bg-zinc-800 dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
